apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bb2t4dtyp-go
  janus-idp.io/tekton: bb2t4dtyp-go
  backstage.io/kubernetes-id: bb2t4dtyp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bb2t4dtyp-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
