apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bb2t4dtyp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bb2t4dtyp-go 
  name: bb2t4dtyp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bb2t4dtyp-go 
